export const ICONS = {
  menu: "eva:menu-outline",
  user: "ix:user-profile",
  language: "ix:earth-filled",
  instagram: "carbon:logo-instagram",
  likeHeart: "system-uicons:heart",
  removeLikeHeart: "system-uicons:heart-remove",
  moon: "material-symbols:dark-mode",
  sun: "material-symbols:sunny-rounded",
  cart: "material-symbols:remove-shopping-cart",
  arrowRight: "mdi:arrow-right-thin",
  colorPalette: "eva:color-palette-outline",
  cursorClick: "heroicons-outline:cursor-click",
  heartsFace: "fa-regular:grin-hearts",
  deliveryTruckSpeed: "material-symbols:delivery-truck-speed-outline-rounded",
  creditScore: "material-symbols:credit-score-outline-rounded",
  thumbnailPreview: "carbon:thumbnail-preview",
  heartHand: "mingcute:hand-heart-line",
} as const;
