name: "[KC/frontend] Build"

on:
  pull_request:
    paths:
      - frontend/**
      - .github/workflows/frontend.yml
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: frontend-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: pnpm init
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install
      - name: Postinstall
        run: pnpm postinstall

      - name: Format check
        run: pnpm run format-check
      - name: Type check
        run: pnpm run type-check

      - name: Build
        run: pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: |
            dist/
            build/
