name: KC/frontend

on:
  pull_request:
    paths:
      - frontend/**
      - .github/workflows/frontend.yml

concurrency:
  group: frontend-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Format check
        run: pnpm run format-check
      - name: Type check
        run: pnpm run type-check

      - name: Build
        run: pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: |
            dist/
            build/
