name: "KC-CI"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  kc_ci:
    name: KC-CI
    runs-on: ubuntu-latest
    outputs:
      require_kc_frontend_checks: ${{ steps.frontend_checks.outputs.require }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: frontend_checks
        run: |
          CHANGES=$(git diff --name-only origin/${{ github.base_ref }} | grep -E '^(apps/frontend|packages/shared)' | head -n 1 | wc -l)
          echo "require=$CHANGES" >> "$GITHUB_OUTPUT"

  kc_frontend_checks:
    name: KC Frontend Checks
    needs: kc_ci
    runs-on: ubuntu-latest
    if: needs.kc_ci.outputs.require_kc_frontend_checks == '1'

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install

      - name: Check types
        run: pnpm --filter frontend run type-check

      - name: Check formatting
        run: pnpm --filter frontend run format-check
